version: "2"

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
  settings:
    staticcheck:
      checks:
        - all
  exclusions:
    generated: lax

formatters:
  enable:
    - gofmt
    - goimports
